### ISSUE TITLE
Two types of nullable bytes

### ISSUE THREAD

**Issue by aovestdipaperino** [tisonkun/kafka-api#6]
I just realized that there are two ways to encode nullable bytes (or bytes array).
For some messages the length is either varint or int16 (which is what is currently implemented)
For some other messages (JoinGroupResponse, JoinGroupRequest, SyncGroupResponse) it's not an int16 but an int32.
This is not documented in the protocol unfortunately. :(

**Comment by tisonkun** [comment]
Closed as the development has been moved to [Morax](https://github.com/tisonkun/morax/) under [`api/kafka-api`](https://github.com/tisonkun/morax/tree/main/api/kafka-api).

The issue seems related to a bug in the `kafka-api` early version. The Kafka official protocol define these type of length: https://kafka.apache.org/protocol.html#protocol_types


<img width="805" alt="image" src="https://github.com/user-attachments/assets/6b9a829b-c977-4476-94eb-ba8747fbbda5">
